# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180605_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alarm_paper',
            field=models.BooleanField(default=True),
        ),
    ]
