"""boards URL Configuration"""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^(?P<table>\d+)/$',
        views.show_list,
        name='show_list_0'
    ),
    url(
        r'^(?P<table>\d+)/(?P<page>\d+)/$',
        views.show_list,
        name='show_list'
    ),
    url(
        r'^search/(?P<search_type>.*)/(?P<search_word>.*)/(?P<table>\d+)/(?P<page>\d+)/$',
        views.show_list,
        name='show_search_article',
    ),
    url(
        r'^search_reply/(?P<search_type>.*)/(?P<search_word>.*)/(?P<table>\d+)/(?P<page>\d+)/$',
        views.search_reply,
        name='search_reply',
    ),
    url(
        r'^search/article/(?P<table>\d+)/(?P<search_type>\w+)/(?P<search_word>.*)/$',
        views.search_article,
        name='search_article'
    ),
    url(
        r'^delete_reply/(?P<id>\d+)/$',
        views.delete_reply,
        name='delete_reply'
    ),
    url(
        r'^restore_reply/(?P<id>\d+)/$',
        views.restore_reply,
        name='restore_reply'
    ),
    url(
        r'^delete_reply_permanently/(?P<id>\d+)/$',
        views.delete_reply_permanently,
        name='delete_reply_permanently'
    ),
    url(
        r'^(?P<table>\d+)/new/$',
        views.new_article,
        name='new_article'
    ),
    url(
        r'^article/(?P<id>\d+)/$',
        views.show_article,
        name='show_article'
    ),
    url(
        r'^article/(?P<id>\d+)/(?P<table>\d+)/$',
        views.show_article,
        name='show_table_article'
    ),
    url(
        r'^article/(?P<id>\d+)/edit/$',
        views.edit_article,
        name='edit_article'
    ),
    url(
        r'^article/(?P<id>\d+)/delete/$',
        views.delete_article,
        name='delete_article',
        kwargs={'stay': False}
    ),
    url(
        r'^post/(?P<id>\d+)/delete_and_stay/$',
        views.delete_article,
        name='delete_and_stay',
        kwargs={'stay': True}
    ),
    url(
        r'^article/(?P<id>\d+)/delete_permanently/$',
        views.delete_article_permanently,
        name='delete_article_permanently'
    ),
    url(
        r'^article/(?P<id>\d+)/restore/$',
        views.restore_article,
        name='restore_article'
    ),
    url(
        r'^dashboard/(?P<condition>.*)/$',
        views.dashboard,
        name='dashboard'
    ),
    url(
        r'^dashboard_article/(?P<status>.*)/(?P<table>\d+)/(?P<page>\d+)/$',
        views.dashboard_article,
        name='dashboard_article'
    ),
    url(
        r'^dashboard_reply/(?P<status>.*)/(?P<page>\d+)/$',
        views.dashboard_reply,
        name='dashboard_reply'
    ),
]
