# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, default='', related_name='board_dislike_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, default='', related_name='board_like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
